<div class="page-header">
  <h1>Users</h1>
</div>

<input type="hidden" id="toggleUrl" value="<?=$this->url('application/default', ['controller'=>'auth', 'action'=>'toggle'])?>" />

<style>
table#usersTbl td:nth-child(1) {
  text-align:center;
  width: 24px;
}
table#usersTbl td:nth-child(5) {
  text-align:center;
  width: 10%;
}
</style>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <table class="table table-striped table-bordered table-condensed" id="usersTbl" data-table data-url="<?=$this->url('application/default', ['controller' => 'auth', 'action' => 'list'])?>" data-method="list" data-table-convert-row-func="convertUserRow" data-checkbox-class="userCheckbox">
      <thead>
        <tr>
          <th></th>
          <th>Login</th>
          <th>Name</th>
          <th>Email</th>
          <th>Active</th>
        </tr>
      </thead>
      <tbody>
        <tr class="info">
          <td colspan="5"><center>Loading...</center></td>
        </tr>
      </tbody>
    </table>

    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-table-button="#usersTbl"><i class="glyphicon glyphicon-trash"></i> Delete</button>
    <button type="button" class="btn btn-info" data-table-refresh="#usersTbl"><i class="glyphicon glyphicon-refresh"></i> Refresh</button>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editUserModal"><i class="glyphicon glyphicon-plus"></i> Add user</button>
  </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Delete confirmation</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete following users?</p>
        <ul id="deleteUsersList">
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="deleteConfirmBtn" data-button data-url="<?=$this->url('application/default', ['controller' => 'auth', 'action' => 'delete'])?>" data-params="{}" data-callback="refreshUsersTable"><i class="glyphicon glyphicon-trash"></i> Delete</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editUserModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="login">Login: </label>
          <input type="text" class="form-control" placeholder="Login" id="login" autocomplete="off" />
        </div>
        <div class="form-group">
          <label for="name">Name: </label>
          <input type="text" class="form-control" placeholder="Name" id="name" autocomplete="off" />
        </div>
        <div class="form-group">
          <label for="email">Email: </label>
          <input type="text" class="form-control" placeholder="Email" id="email" autocomplete="off" />
        </div>
        <div class="form-group">
          <label for="password">Password: </label>
          <input type="password" class="form-control" placeholder="Password" id="password" autocomplete="off" />
        </div>
        <div class="form-group">
          <label for="password2">Password (confirmation): </label>
          <input type="password" class="form-control" placeholder="Password (confirmation)" id="password2" autocomplete="off" />
        </div>
        <div class="checkbox">
          <label><input type="checkbox" name="active" id="active" value="1"> Active</label>
        </div>
        <input type="hidden" id="userId" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-confirm-button data-button data-url="<?=$this->url('application/default', ['controller' => 'auth', 'action' => 'save'])?>" data-params="{}" data-callback="refreshUsersTable" data-prepare="prepareSaveUser"><i class="glyphicon glyphicon-check"></i> Save</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
function convertUserRow(user) {
    var row = $('<tr></tr>').data('user',user);

    var editLink = $('<a href="#" data-toggle="modal" data-target="#editUserModal">'+user.login+'</a>');
    var toggleBtn = $('<button type="button" class="btn btn-xs user-toggle"></button>').addClass(user.active ? 'btn-success' : 'btn-danger').text(user.active ? 'Active' : 'Inactive');
    toggleBtn.data("url",$("#toggleUrl").val());
    toggleBtn.data("params",{id: user.id});
    toggleBtn.data("callback","toggleUserUpdate");
    toggleBtn.dataButton("init");

    row.append($('<td></td>').append(editLink));
    row.append($('<td></td>').text(user.name));
    row.append($('<td></td>').text(user.email));
    row.append($('<td></td>').append(toggleBtn));

    return row;
}

function onDeleteModalShow() {
    if($("#usersTbl input:checked").length == 0) {
        return false;
    }

    var ids = new Array();
    $("#deleteUsersList").empty();
    $("#usersTbl input:checked").each(function(id,input){
        var user = $(input).parents("tr:first").data("user");
        var li = $("<li>"+user.login+" - "+user.name+"</li>");
        $("#deleteUsersList").append(li);
        ids.push(user.id);
    });
    $("#deleteConfirmBtn").dataButton("setParams",{ids: ids});
}

function onEditUserModalShow(e) {
    var user = $(e.relatedTarget).parents("tr:first").data("user");

    $("#editUserModal .form-group").removeClass("has-error");
    if(user) {
        $("#editUserModal .modal-title").text("Edit user details");
        $("#userId").val(user.id);
        $("#login").val(user.login);
        $("#name").val(user.name);
        $("#email").val(user.email);
        $("#password").val("");
        $("#password2").val("");
        $("#active")[0].checked = user.active;
    } else {
        $("#editUserModal .modal-title").text("New user details");
        $("#userId").val("");
        $("#login").val("");
        $("#name").val("");
        $("#email").val("");
        $("#password").val("");
        $("#password2").val("");
        $("#active")[0].checked = true;
    }
}

function validateUser() {
    $("#editUserModal .form-group").removeClass("has-error");
    if($("#login").val().length < 4) {
        $("#login").parent().addClass("has-error");
        msg('error',"Login must be at least 4 characters long");
        $("#login").focus();
        return false;
    }
    if($("#name").val().length == 0) {
        $("#name").parent().addClass("has-error");
        msg('error',"Name must not be empty");
        $("#name").focus();
        return false;
    }
    if(!$("#email").val().match(/.+@.+/gi)) {
        $("#email").parent().addClass("has-error");
        msg('error',"Invalid email specified");
        $("#email").focus();
        return false;
    }
    if(!($("#userId").val() != "" && $("#password").val() == "" && $("#password2").val() == "")) {
        if($("#password").val().length < 8) {
            $("#password").parent().addClass("has-error");
            msg('error',"Password must be at least 8 characters long");
            $("#password").focus();
            return false;
        }
        if($("#password").val() != $("#password2").val()) {
            $("#password").parent().addClass("has-error");
            $("#password2").parent().addClass("has-error");
            msg('error',"Passwords do not match");
            $("#password").focus();
            return false;
        }
    }
    return true;
}

function prepareSaveUser() {
    if(!validateUser()) {
        return false;
    }
    var user = {
        login: $("#login").val(),
        name: $("#name").val(),
        email: $("#email").val(),
        active: $("#active").prop('checked')
    }
    if($("#userId").val() != "") {
        user.id = $("#userId").val();
    }
    if($("#password").val() != "") {
        user.password = $("#password").val();
    }

    this.button.dataButton("setParams",{user: user});
    return true;
}

function refreshUsersTable() {
    $(".modal").modal('hide');
    $("#usersTbl").dataTable("refresh");
}

function toggleUserUpdate(user) {
    var button = $(this.button);
    var row = button.parents("tr:first");
    var rowUser = row.data("user");
    rowUser.active = user.active;
    row.data("user",rowUser);

    if(user.active) {
        button.removeClass("btn-danger").addClass("btn-success").text("Active");
    } else {
        button.addClass("btn-danger").removeClass("btn-success").text("Inactive");
    }
}

$(document).ready(function(){
    $("#deleteModal").on('show.bs.modal',onDeleteModalShow);
    $("#editUserModal").on('show.bs.modal',onEditUserModalShow);
});
</script>
