<form class="form-inline" method="post" action="<?=$this->url('application', ['controller' => 'auth', 'action' => 'login'])?>" id="login-form">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-primary">
        <div class="panel-heading"><h3>Demo servers initialization process</h3></div>
        <div class="panel-body">
          <div><b>Login: <?=$this->user->login?></b></div>
          <div><b>Password: <?=$this->password?></b></div>
        </div>
      </div>
    </div>
  </div>
</form>
