<form class="form-inline" method="post" action="<?=$this->url('application', ['controller' => 'auth', 'action' => 'login'])?>" id="login-form">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-primary">
        <div class="panel-heading"><h3>Template Login</h3></div>
        <div class="panel-body">
          <?php if ($this->error): ?>
            <div class="alert alert-error">Invalid login and/or password</div>
          <?php endif; ?>
          <input class="col-md-5" type="text" name="login" id="login" placeholder="Login" />
          <input class="col-md-5 col-md-offset-1" type="password" name="password" placeholder="Password" />
        </div>
        <div class="panel-footer">
          <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-log-in"></i> Login</button>
        </div>
      </div>
    </div>
  </div>
</form>

<script type="text/javascript">
$(document).ready(function(){
    $('#login').focus();
});
</script>
