<div class="page-header">
  <h1>Zync <small>Zend Unified Sync Manager</small></h1>
</div>

<div class="row">

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Header</h3>
      </div>
      <div class="panel-body">
        <p>Body</p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Header</h3>
      </div>
      <div class="panel-body">
        <p>Body</p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Header</h3>
      </div>
      <div class="panel-body">
        <p>Body</p>
      </div>
    </div>
  </div>
</div>
